version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: products
      MYSQL_USER: user # Set a user for the database
      MYSQL_PASSWORD: sa
      MYSQL_ROOT_PASSWORD: sasa
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: